
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: homework
  namespace: prom-workshop
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: homework
  template:
    metadata:
      name: homework
      labels:
        app: homework
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10100"
    spec:
      containers:
      - name: homework
        image: hbkmustang/centos-xinetd:12.0
        ports:
        - name: web
          containerPort: 10100
        resources:
          limits:
            memory: "128Mi"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    name: homework
  name: homework
  namespace: prom-workshop
spec:
  type: LoadBalancer
  selector:
    app: homework
  ports:
  - name: homework
    protocol: TCP
    port: 10100
    targetPort: web
